/* Full master catalog: no profile or country filter unless explicitly selected. */
let catalogQuery='',catalogCategory='',catalogLimit=48;
function openFullCatalog(){
 showModalSheet('<div class="catalog-heading"><small>ENTDECKEN</small><h2>Der ganze Produktkatalog</h2><p>Alle Altersbereiche. Suche nach Produkt, Marke oder Barcode.</p></div><div class="catalog-filters"><label>Suche<input id="fullCatalogSearch" type="search" placeholder="Name, Marke oder Barcode" autocomplete="off"></label><label>Bereich<select id="fullCatalogCategory"><option value="">Alle Bereiche</option><option value="erwachsen_gesicht">Erwachsene</option><option value="jugend">Jugend</option><option value="baby_kind">Baby & Kind</option></select></label></div><p id="fullCatalogCount" role="status"></p><div id="fullCatalogResults" class="catalog-grid"></div><button id="fullCatalogMore" class="catalog-more">Weitere Produkte anzeigen</button><p class="evidence-scope">Katalogeinträge können dasselbe Produkt in mehreren Altersbereichen enthalten. Ein Eintrag ist keine Empfehlung für dein Profil. Produktangaben können sich ändern.</p>');
 const search=document.getElementById('fullCatalogSearch'),category=document.getElementById('fullCatalogCategory');search.value=catalogQuery;category.value=catalogCategory;
 search.oninput=()=>{catalogQuery=search.value;catalogLimit=48;renderFullCatalog();};category.onchange=()=>{catalogCategory=category.value;catalogLimit=48;renderFullCatalog();};document.getElementById('fullCatalogMore').onclick=()=>{catalogLimit+=48;renderFullCatalog();};renderFullCatalog();
}
function renderFullCatalog(){
 const all=window.fullCatalogRows||[];const q=catalogQuery.trim().toLocaleLowerCase();const found=all.filter(p=>(!catalogCategory||p.katalog===catalogCategory)&&(!q||[p.name,p.brand,p.ean].join(' ').toLocaleLowerCase().includes(q)));
 const area=document.getElementById('fullCatalogResults');if(!area)return;area.replaceChildren();
 document.getElementById('fullCatalogCount').textContent=all.length?found.length+' von '+all.length+' Katalogeinträgen · '+Math.min(catalogLimit,found.length)+' angezeigt':'Katalog wird geladen. Bitte gleich erneut öffnen.';
 for(const p of found.slice(0,catalogLimit)){const card=document.createElement('button');card.className='catalog-product';const brand=document.createElement('small'),title=document.createElement('strong'),meta=document.createElement('span');brand.textContent=p.brand||'Marke nicht hinterlegt';title.textContent=p.name;meta.textContent=({'erwachsen_gesicht':'Erwachsene',jugend:'Jugend',baby_kind:'Baby & Kind'}[p.katalog]||p.katalog)+(p.ean?' · '+p.ean:'');card.append(brand,title,meta);card.onclick=()=>openCatalogEntry(p);area.append(card);}
 if(!found.length&&all.length){const empty=document.createElement('p');empty.textContent='Kein Treffer. Versuche eine kürzere Bezeichnung oder einen anderen Bereich.';area.append(empty);}
 document.getElementById('fullCatalogMore').hidden=found.length<=catalogLimit;
}
function openCatalogEntry(p){
 const e=escapeHtml;showModalSheet('<button class="catalog-back" onclick="openFullCatalog()">← Zurück zum Katalog</button><div class="detail-heading"><small>'+e(p.brand||'Produkt')+'</small><h2>'+e(p.name)+'</h2></div><p>Barcode: '+e(p.ean||'nicht hinterlegt')+'</p><p>Bereich: '+e(({baby_kind:'Baby & Kind',jugend:'Jugend',erwachsen_gesicht:'Erwachsene'}[p.katalog]||p.katalog))+'</p><p class="evidence-scope">Diese Katalogdaten enthalten keine vollständige Rezeptur. Deshalb lässt sich daraus allein kein vollständiger Kombinationscheck erstellen.</p>'+( /^https:\/\//.test(p.source_url||'')?'<a class="catalog-source" href="'+e(p.source_url)+'" target="_blank" rel="noopener noreferrer">Produktquelle öffnen ↗</a>':'')+'<p class="evidence-scope">Datenstand: '+e(p.checked_at||'nicht hinterlegt')+'</p>');
}
